USE ic2;

INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('ART_A1','Articulo A1','GNC',7, "Articulos","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('ART_A2','Articulo A2','GNC',7, "Articulos","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('ART_B','Articulo B','GNC',7, "Articulos" ,"A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('ART_C','Articulo C','GNC',7, "Articulos","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('ART_D','Articulo D','GNC',5, "Articulos","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('N_A1','Nota cientifica A1','GNC',5, "Notas Cientificas","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('N_A2','Nota cientifica A2','GNC',5, "Notas Cientificas","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('N_B','Nota cientifica B','GNC',5, "Notas Cientificas","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('N_C','Nota cientifica C','GNC',5, "Notas Cientificas","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('N_D','Nota cientifica D','GNC',5, "Notas Cientificas","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('LIB_A1','Libro A1','GNC',7, "Libros","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('LIB_A','Libro A','GNC',7, "Libros","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('LIB_B','Libro B','GNC',7, "Libros","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('CAP_LIB_A1','Capitulo libro A1','GNC',5, "Capitulos libro","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('CAP_LIB_A','Capitulo libro A','GNC',5, "Capitulos libro","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('CAP_LIB_B','Capitulo libro B','GNC',5, "Capitulos libro","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PA1','Patente A, PCT','GNC',10, "Patentes","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MA1','Modelo A, PCT','GNC',10, "Modelos utilidad","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PA2','Patente A, tradicional','GNC',10, "Patentes","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MA2','Modelo A, tradicional','GNC',10, "Modelos utilidad","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PA3','Patente A, PCT','GNC',10, "Patentes","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MA3','Modelo A, PCT','GNC',10, "Modelos utilidad","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PA4','Patente A, tradicional','GNC',10, "Patentes","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MA4','Modelo A, tradicional','GNC',10, "Modelos utilidad","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PB1','Patente B, PCT','GNC',10, "Patentes","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MB1','Modelo B, PCT','GNC',10, "Modelos utilidad","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PB2','Patente B, PCT','GNC',10, "Patentes","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MB2','Modelo B, PCT','GNC',10, "Modelos utilidad","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PB3','Patente B, tradicional','GNC',10, "Patentes","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MB3','Modelo B, tradicional','GNC',10, "Modelos utilidad","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PB4','Patente B, PCT','GNC',10, "Patentes","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MB4','Modelo B, PCT','GNC',10, "Modelos utilidad","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PB5','Patente B, tradicional','GNC',10, "Patentes","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MB5','Modelo B, tradicional','GNC',10, "Modelos utilidad","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PC','Patente C, contrato explotacion','GNC',10, "Patentes","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MC','Modelo C, contrato explotacion','GNC',10, "Modelos utilidad","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('VV_A1','Variedad vegetal A1','GNC',10, "Variedades vegetales","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('VV_A2','Variedad vegetal A2','GNC',10, "Variedades vegetales","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('VV_A3','Variedad vegetal A3','GNC',10, "Variedades vegetales","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('VV_A4','Variedad vegetal A4','GNC',10, "Variedades vegetales","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('VV_B1','Variedad vegetal B1','GNC',10, "Variedades vegetales","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('VV_B2','Variedad vegetal B2','GNC',10, "Variedades vegetales","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('VV_B3','Variedad vegetal B3','GNC',10, "Variedades vegetales","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('VV_B4','Variedad vegetal B4','GNC',10, "Variedades vegetales","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('VA_A','Nueva raza animal','GNC',10, "Variedades animales","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('VA_B','Poblaciones mejoradas de razas pecuarias','GNC',10, "Razas pecuarias","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('DI_A','Diseno industrial A','DTI',5, "Disenos industriales","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('DI_B','Diseno industrial B','DTI',5, "Disenos industriales","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('ECI_A','Esquema circuito A','DTI',5, "Esquemas circuito","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('SF_A','Software A','DTI',5, "Softwares","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('SF_B','Software B (No tiene validez)','DTI',5, "Softwares","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PP_A','Planta piloto A','DTI',5, "Plantas piloto","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PI_A','Prototipo industrial A','DTI',5, "Prototipos industriales","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('SD','Signos distintivos','DTI',5, "Signos distintivos","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PN','Productos nutraceuticos','DTI',5, "Productos nutraceuticos","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('CC','Colecciones cientificas','DTI',5, "Colecciones cientificas","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('NRC_A','Nuevo registro cientifico publicado en articulo cientifico','DTI',5, "Registros cientificos","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('NRC_B','Nuevo registro cientifico','DTI',5, "Registros cientificos","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('SE','Secreto empresarial','DTI',5, "Secretos Empresarial","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('EBT_A','Empresa base tecnologica A','DTI',5, "Empresas base tecnologica","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('EBT_B','Empresa base tecnologica B','DTI',5, "Empresas base tecnologica","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('ICC_A','Empresas creativas y culturales A','DTI',5, "Empresas creativas y culturales","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('ICC_B','Empresas creativas y culturales B','DTI',5, "Empresas creativas y culturales","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('IG_A1','Innnovacion generada en la gestion empresarial A1','DTI',5, "Innovaciones generadas en la gestion empresarial","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('IG_A2','Innnovacion generada en la gestion empresarial A2','DTI',5, "Innovaciones generadas en la gestion empresarial","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('IG_B1','Innnovacion generada en la gestion empresarial B1','DTI',5, "Innovaciones generadas en la gestion empresarial","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('IG_B2','Innnovacion generada en la gestion empresarial B2','DTI',5, "Innovaciones generadas en la gestion empresarial","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('IPP','Innnovacion en procedimiento y servicio','DTI',5, "Innovaciones en procesos y procedimientos","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('RNL_A','Regulacion norma A','DTI',5, "Regulaciones y normas","A1");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('RNL_B','Regulacion norma B','DTI',5, "Regulaciones y normas","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('RNR','Regulacion norma espectro radioelectrico','DTI',5, "Regulaciones y normas","A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('RNT','Regulacion norma tecnica','DTI',5, "Regulaciones y normas","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('RNPC','Guia de practica clinica','DTI',5, "Guias de practica clinica","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('GMCF','Guia de manejo clinico forense','DTI',5, "Guias de manejo clinico forense","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('MADV','Manuales y Modelos de atencion diferencial a victimas','DTI',5, "Modelos atencion diferencial","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PAU','Protocolos de atención a usuarios víctimas (pacientes)','DTI',5, "Protocolos de atencion","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PVE','Protocolos de vigilancia epidemiologica','DTI',5, "Protocolos de vigilancia epidemiologica","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('AL','Acuerdo de ley','DTI',5, "Acuerdos de ley","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('RNPL','Proyecto de ley','DTI',5, "Proyectos de ley","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('CT','Conceptos tecnicos','DTI',5, "Conceptos tecnicos","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('INF','Informe tecnico final','DTI',5, "Informe tecnico","B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PPC','Participacion ciudadana proyectos CTI','ASC',5, "Participacion ciudadana proyectos CTI","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('EPC','Espacios participacion ciudadana CTI','ASC',5, "Espacios participacion ciudadana CTI","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('EPA','Estrategias pedagogicas fomento CTI','ASC',5, "Estrategias pedagogicas fomento CTI","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PCC','Estrategias comunicacion conocimiento','ASC',5, "Estrategias comunicacion conocimiento","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('GC','Generacion de contenidos','ASC',5, "Generaciones contenido","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('GC_ART','Generacion contenido impreso articulo','ASC',5, "Generaciones contenido","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('GC_LIB','Generacion contenido impreso libro','ASC',5, "Generaciones contenido","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('GC_CAP_LIB','Generacion contenido impreso capitulo libro','ASC',5, "Generaciones contenido","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('EC_A','Evento cientifico A','ASC',5, "Eventos cientificos","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('EC_B','Evento cientifico B','ASC',5, "Eventos cientificos","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('RC_A','Red conocimiento A','ASC',5, "Redes de conocimiento","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('RC_B','Red conocimiento B','ASC',5, "Redes de conocimiento","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('WP','Documento trabajo','ASC',5, "Documentos trabajo","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('BOL','Boletin divulgativo','ASC',5, "Boletin","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('ERL','Edicion de revista o libro','ASC',5, "Ediciones","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('IFI','Informe final investigacion','ASC',5, "Informes de investigacion","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('CON_CT','Consultoria cientifica-tecnologica','ASC',5, "Consultorias","ASC");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('TD_A','Tesis doctorado A','FRH',5, "Trabajos dirigidos","FRH_A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('TD_B','Tesis doctorado B','FRH',5, "Trabajos dirigidos","FRH_A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('TM_A','Tesis maestria A','FRH',5, "Trabajos dirigidos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('TM_B','Tesis maestria B','FRH',5, "Trabajos dirigidos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('TP_A','Trabajo pregrado A','FRH',5, "Trabajos dirigidos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('TP_B','Trabajo pregrado B','FRH',5, "Trabajos dirigidos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PID_A','Proyecto investigacion desarrollo A','FRH',5, "Proyectos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PID_B','Proyecto investigacion desarrollo B','FRH',5, "Proyectos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PID_C','Proyecto investigacion desarrollo C','FRH',5, "Proyectos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PIC_A','Proyecto investigacion-creacion A','FRH',5, "Proyectos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PIC_B','Proyecto investigacion-creacion B','FRH',5, "Proyectos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PIC_C','Proyecto investigacion-creacion C','FRH',5, "Proyectos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PF_A','Proyecto ID+I A','FRH',5, "Proyectos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PF_B','Proyecto ID+I B','FRH',5, "Proyectos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('PE','Proyecto extension social CTI','FRH',5, "Proyectos","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('AP_A','Apoyo programa formacion doctorado','FRH',5, "Apoyo programa formacion","FRH_A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('AP_B','Apoyo programa formacion maestria','FRH',5, "Apoyo programa formacion","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('AP_C','Apoyo programa formacion cursos doctorado','FRH',5, "Apoyo programa formacion","FRH_A");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('AP_D','Apoyo programa formacion cursos maestria','FRH',5, "Apoyo programa formacion","FRH_B");
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento,i_ventana_observacion, c_tipo_producto, c_tipo_produccion) values ('APO','Acompanamiento y asesoria Programa Ondas','FRH',5, "Asesorias programa ondas","FRH_B");