USE ic2;

INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('ART_A1','Artículo A1','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('ART_A2','Artículo A2','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('ART_B','Artículo B','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('ART_C','Artículo C','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('ART_D','Artículo D','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('N_A1','Nota científica A1','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('N_A2','Nota científica A2','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('N_B','Nota científica B','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('N_C','Nota científica C','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('N_D','Nota científica D','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('LIB_A1','Libro A1','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('LIB_A','Libro A','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('LIB_B','Libro B','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('CAP_LIB_A1','Capítulo libro A1','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('CAP_LIB_A','Capítulo libro A','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('CAP_LIB_B','Capítulo libro B','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PA1','Patente A, PCT','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('MA1','Modelo A, PCT','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PA2','Patente A, tradicional','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('MA2','Modelo A, tradicional','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PA3','Patente A, PCT','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('MA3','Modelo A, PCT','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PA4','Patente A, tradicional','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('MA4','Modelo A, tradicional','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PB1','Patente B, PCT','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('MB1','Modelo B, PCT','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PB2','Patente B, PCT','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('MB2','Modelo B, PCT','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PB3','Patente B, tradicional','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('MB3','Modelo B, tradicional','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PB4','Patente B, PCT','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('MB4','Modelo B, PCT','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PB5','Patente B, tradicional','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('MB5','Modelo B, tradicional','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PBC','Patente C, contrato explotacion','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('MBC','Modelo C, contrato explotacion','GNC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('DI_A','Diseño industrial A','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('DI_B','Diseño industrial B','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('ECI_A','Esquema circuito A','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('SF_A','Software A','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PP_A','Planta piloto A','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PI_A','Prototipo industrial A','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('SD','Signos distintivos','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PN','Productos nutracéuticos','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('CC','Colecciones científicas','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('NRC_A','Nuevo registro científico publicado en artículo científico','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('NRC_B','Nuevo registro científico','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('SE','Secreto empresarial','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('EBT_A','Empresa base tecnológica A','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('EBT_B','Empresa base tecnológica B','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('CT','Conceptos técnicos','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('INF','Informe técnico final','DTI',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PPC','Participación ciudadana proyectos CTI','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('EPC','Espacios participación ciudadana CTI','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('EPA','Estrategias pedagógicas fomento CTI','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PCC','Estrategias comunicación conocimiento','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('GC','Generación de contenidos','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('GC_ART','Generación contenido impreso articulo','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('GC_LIB','Generación contenido impreso libro','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('GC_CAP_LIB','Generación contenido impreso capítulo libro','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('EC_A','Evento cientifico A','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('EC_B','Evento cientifico B','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('RC_A','Red conocimiento A','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('RC_B','Red conocimiento B','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('WP','Documento trabajo','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('BOL','Boletín divulgativo','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('ERL','Edición de revista o libro','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('IFI','Informe final investigación','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('CON_CT','Consultoría científica-tecnológica','ASC',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('TD_A','Tesis doctorado A','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('TD_B','Tesis doctorado B','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('TM_A','Tesis maestría A','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('TM_B','Tesis maestría B','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('TP_A','Trabajo pregrado A','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('TP_B','Trabajo pregrado B','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PID_A','Proyecto investigación desarrollo A','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PID_B','Proyecto investigación desarrollo B','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PID_C','Proyecto investigación desarrollo C','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PIC_A','Proyecto investigacion-creación A','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PIC_B','Proyecto investigacion-creación B','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PIC_C','Proyecto investigacion-creación C','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PF_A','Proyecto ID+I A','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PF_B','Proyecto ID+I B','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('PE','Proyecto extensión social CTI','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('AP_A','Apoyo programa formación doctorado','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('AP_B','Apoyo programa formación maestría','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('AP_C','Apoyo programa formación cursos doctorado','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('AP_D','Apoyo programa formación cursos maestría','FRH',5);
INSERT INTO categoria (k_codigo,n_nombre,c_tipo_produccion,i_ventana_observacion) values ('APO','Acompañamiento y asesoría Programa Ondas','FRH',5);