USE ic2;

INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('ART_A1','Artículo A1','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('ART_A2','Artículo A2','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('ART_B','Artículo B','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('ART_C','Artículo C','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('ART_D','Artículo D','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('LIB_A1','Libro A1','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('LIB_A','Libro A','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('LIB_B','Libro B','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('CAP_LIB_A1','Capítulo libro A1','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('CAP_LIB_A','Capítulo libro A','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('CAP_LIB_B','Capítulo libro B','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PA1-MA1','Patente A, PCT','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PA2-MA2','Patente A, tradicional','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PA3-MA3','Patente A, PCT','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PA4-MA4','Patente A, tradicional','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PB1-MB1','Patente B, PCT','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PB2-MB2','Patente B, PCT','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PB3-MB3','Patente B, tradicional','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PB4-MB4','Patente B, PCT','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PB5-MB5','Patente B, tradicional','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PBC-MC','Patente C, contrato explotacion','GNC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('DI_A','Diseño industrial A','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('DI_B','Diseño industrial B','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('ECI_A','Esquema circuito A','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('SF_A','Software A','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('SF_B','Software B','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PP_A','Planta piloto A','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PI_A','Prototipo industrial A','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('SD','Signos distintivos','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('SE','Secreto empresarial','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('EBT_A','Empresa base tecnológica A','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('EBT_B','Empresa base tecnológica B','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('IPP','Innovación procedimiento servicio','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('CON_CT','Consultoría científica-tecnológica','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('INF','Informe técnico final','DTI');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PPC','Participación ciudadana proyectos CTI','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('EPC','Espacios participación ciudadana CTI','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('EPA','Estrategias pedagógicas fomento CTI','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PCC','Estrategias comunicación conocimiento','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('GC_ART','Generación contenido impreso articulo','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('GC_LIB','Generación contenido impreso libro','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('GC_CAP_LIB','Generación contenido impreso capítulo libro','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('EC_A','Evento cientifico A','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('EC_B','Evento cientifico B','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('RC_A','Red conocimiento A','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('RC_B','Red conocimiento B','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('WP','Documento trabajo','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('BOL','Boletín divulgativo','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('ERL','Edición de revista o libro','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('IFI','Informe final investigación','ASC');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('TD_A','Tesis doctorado A','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('TD_B','Tesis doctorado B','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('TM_A','Tesis maestría A','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('TM_B','Tesis maestría B','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('TP_A','Trabajo pregrado A','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('TP_B','Trabajo pregrado B','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PID_A','Proyecto investigación desarrollo A','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PID_B','Proyecto investigación desarrollo B','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PID_C','Proyecto investigación desarrollo C','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PIC_A','Proyecto investigacion-creación A','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PIC_B','Proyecto investigacion-creación B','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PIC_C','Proyecto investigacion-creación C','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PF_A','Proyecto ID+I A','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PF_B','Proyecto ID+I B','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('PE','Proyecto extensión social CTI','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('AP_A','Apoyo programa formación doctorado','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('AP_B','Apoyo programa formación maestría','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('AP_C','Apoyo programa formación cursos doctorado','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('AP_D','Apoyo programa formación cursos maestría','FRH');
INSERT INTO categoria (k_codigo,n_nombre,c_area_conocimiento) values ('APO','Acompañamiento y asesoría Programa Ondas','FRH');