USE ic2;

INSERT INTO pais (k_codigo,n_nombre) VALUES (004,'Afganistán');
INSERT INTO pais (k_codigo,n_nombre) VALUES (008,'Albania');
INSERT INTO pais (k_codigo,n_nombre) VALUES (276,'Alemania');
INSERT INTO pais (k_codigo,n_nombre) VALUES (020,'Andorra');
INSERT INTO pais (k_codigo,n_nombre) VALUES (024,'Angola');
INSERT INTO pais (k_codigo,n_nombre) VALUES (660,'Anguila');
INSERT INTO pais (k_codigo,n_nombre) VALUES (028,'Antigua y Barbuda');
INSERT INTO pais (k_codigo,n_nombre) VALUES (530,'Antillas Neerlandesas');
INSERT INTO pais (k_codigo,n_nombre) VALUES (010,'Antártida');
INSERT INTO pais (k_codigo,n_nombre) VALUES (682,'Arabia Saudita');
INSERT INTO pais (k_codigo,n_nombre) VALUES (012,'Argelia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (032,'Argentina');
INSERT INTO pais (k_codigo,n_nombre) VALUES (051,'Armenia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (533,'Aruba');
INSERT INTO pais (k_codigo,n_nombre) VALUES (807,'ARY Macedonia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (036,'Australia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (040,'Austria');
INSERT INTO pais (k_codigo,n_nombre) VALUES (031,'Azerbaiyan');
INSERT INTO pais (k_codigo,n_nombre) VALUES (044,'Bahamas');
INSERT INTO pais (k_codigo,n_nombre) VALUES (048,'Bahrein');
INSERT INTO pais (k_codigo,n_nombre) VALUES (050,'Bangladesh');
INSERT INTO pais (k_codigo,n_nombre) VALUES (052,'Barbados');
INSERT INTO pais (k_codigo,n_nombre) VALUES (084,'Belice');
INSERT INTO pais (k_codigo,n_nombre) VALUES (204,'Benin');
INSERT INTO pais (k_codigo,n_nombre) VALUES (060,'Bermudas');
INSERT INTO pais (k_codigo,n_nombre) VALUES (112,'Bielorrusia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (104,'Birmania');
INSERT INTO pais (k_codigo,n_nombre) VALUES (068,'Bolivia, estado plurinacional (de)');
INSERT INTO pais (k_codigo,n_nombre) VALUES (535,'Bonaire, Saint eustatius and Saba');
INSERT INTO pais (k_codigo,n_nombre) VALUES (070,'Bosnia-Herzegovina');
INSERT INTO pais (k_codigo,n_nombre) VALUES (072,'Botswana');
INSERT INTO pais (k_codigo,n_nombre) VALUES (076,'Brasil');
INSERT INTO pais (k_codigo,n_nombre) VALUES (096,'Brunei Darussalam');
INSERT INTO pais (k_codigo,n_nombre) VALUES (100,'Bulgaria');
INSERT INTO pais (k_codigo,n_nombre) VALUES (854,'Burkina Faso');
INSERT INTO pais (k_codigo,n_nombre) VALUES (108,'Burundi');
INSERT INTO pais (k_codigo,n_nombre) VALUES (064,'Buthán');
INSERT INTO pais (k_codigo,n_nombre) VALUES (056,'Bélgica');
INSERT INTO pais (k_codigo,n_nombre) VALUES (132,'Cabo Verde');
INSERT INTO pais (k_codigo,n_nombre) VALUES (116,'Camboya (Kampuchea)');
INSERT INTO pais (k_codigo,n_nombre) VALUES (120,'Camerún');
INSERT INTO pais (k_codigo,n_nombre) VALUES (124,'Canadá');
INSERT INTO pais (k_codigo,n_nombre) VALUES (148,'Chad');
INSERT INTO pais (k_codigo,n_nombre) VALUES (152,'Chile');
INSERT INTO pais (k_codigo,n_nombre) VALUES (156,'China');
INSERT INTO pais (k_codigo,n_nombre) VALUES (196,'Chipre');
INSERT INTO pais (k_codigo,n_nombre) VALUES (170,'Colombia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (174,'Comoras');
INSERT INTO pais (k_codigo,n_nombre) VALUES (188,'Costa Rica');
INSERT INTO pais (k_codigo,n_nombre) VALUES (384,'Costa de Marfil');
INSERT INTO pais (k_codigo,n_nombre) VALUES (191,'Croacia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (192,'Cuba');
INSERT INTO pais (k_codigo,n_nombre) VALUES (531,'Curaçao');
INSERT INTO pais (k_codigo,n_nombre) VALUES (208,'Dinamarca');
INSERT INTO pais (k_codigo,n_nombre) VALUES (212,'Dominica');
INSERT INTO pais (k_codigo,n_nombre) VALUES (218,'Ecuador');
INSERT INTO pais (k_codigo,n_nombre) VALUES (818,'Egipto');
INSERT INTO pais (k_codigo,n_nombre) VALUES (784,'Emiratos Arabes Unidos');
INSERT INTO pais (k_codigo,n_nombre) VALUES (232,'Eritrea');
INSERT INTO pais (k_codigo,n_nombre) VALUES (703,'Eslovaquia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (705,'Eslovenia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (724,'España');
INSERT INTO pais (k_codigo,n_nombre) VALUES (275,'Estado de Palestina');
INSERT INTO pais (k_codigo,n_nombre) VALUES (583,'Estados Federados de Micronesia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (840,'Estados Unidos de América');
INSERT INTO pais (k_codigo,n_nombre) VALUES (233,'Estonia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (231,'Etiopía');
INSERT INTO pais (k_codigo,n_nombre) VALUES (608,'Filipinas');
INSERT INTO pais (k_codigo,n_nombre) VALUES (246,'Finlandia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (250,'Francia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (266,'Gabón');
INSERT INTO pais (k_codigo,n_nombre) VALUES (270,'Gambia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (268,'Georgia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (288,'Ghana');
INSERT INTO pais (k_codigo,n_nombre) VALUES (292,'Gibraltar');
INSERT INTO pais (k_codigo,n_nombre) VALUES (308,'Granada');
INSERT INTO pais (k_codigo,n_nombre) VALUES (300,'Grecia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (304,'Groelandia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (312,'Guadalupe');
INSERT INTO pais (k_codigo,n_nombre) VALUES (316,'Guam');
INSERT INTO pais (k_codigo,n_nombre) VALUES (320,'Guatemala');
INSERT INTO pais (k_codigo,n_nombre) VALUES (328,'Guayana');
INSERT INTO pais (k_codigo,n_nombre) VALUES (254,'Guayana Francesa');
INSERT INTO pais (k_codigo,n_nombre) VALUES (831,'Guernsey');
INSERT INTO pais (k_codigo,n_nombre) VALUES (324,'Guinea');
INSERT INTO pais (k_codigo,n_nombre) VALUES (226,'Guinea Ecuatorial');
INSERT INTO pais (k_codigo,n_nombre) VALUES (624,'Guinea-Bissau');
INSERT INTO pais (k_codigo,n_nombre) VALUES (332,'Haití');
INSERT INTO pais (k_codigo,n_nombre) VALUES (340,'Honduras');
INSERT INTO pais (k_codigo,n_nombre) VALUES (344,'Hong Kong');
INSERT INTO pais (k_codigo,n_nombre) VALUES (348,'Hungría');
INSERT INTO pais (k_codigo,n_nombre) VALUES (356,'India');
INSERT INTO pais (k_codigo,n_nombre) VALUES (360,'Indonesia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (368,'Irak');
INSERT INTO pais (k_codigo,n_nombre) VALUES (372,'Irlanda');
INSERT INTO pais (k_codigo,n_nombre) VALUES (364,'Irán');
INSERT INTO pais (k_codigo,n_nombre) VALUES (074,'Isla Bouvet');
INSERT INTO pais (k_codigo,n_nombre) VALUES (574,'Isla Norfolk');
INSERT INTO pais (k_codigo,n_nombre) VALUES (833,'Isla de Man');
INSERT INTO pais (k_codigo,n_nombre) VALUES (162,'Isla de Navidad');
INSERT INTO pais (k_codigo,n_nombre) VALUES (352,'Islandia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (248,'Islas Aland');
INSERT INTO pais (k_codigo,n_nombre) VALUES (136,'Islas Caimán');
INSERT INTO pais (k_codigo,n_nombre) VALUES (166,'Islas Cocos');
INSERT INTO pais (k_codigo,n_nombre) VALUES (184,'Islas Cook');
INSERT INTO pais (k_codigo,n_nombre) VALUES (234,'Islas Feroe');
INSERT INTO pais (k_codigo,n_nombre) VALUES (239,'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO pais (k_codigo,n_nombre) VALUES (334,'Islas Heard y MacDonald');
INSERT INTO pais (k_codigo,n_nombre) VALUES (238,'Islas Malvinas');
INSERT INTO pais (k_codigo,n_nombre) VALUES (580,'Islas Marianas del Norte');
INSERT INTO pais (k_codigo,n_nombre) VALUES (584,'Islas Marshall');
INSERT INTO pais (k_codigo,n_nombre) VALUES (612,'Islas Pitcairn');
INSERT INTO pais (k_codigo,n_nombre) VALUES (090,'Islas Salomon');
INSERT INTO pais (k_codigo,n_nombre) VALUES (796,'Islas Turcas y Caicos');
INSERT INTO pais (k_codigo,n_nombre) VALUES (581,'Islas Ultramarinas de Estados Unidos');
INSERT INTO pais (k_codigo,n_nombre) VALUES (092,'Islas Virgenes Británicas');
INSERT INTO pais (k_codigo,n_nombre) VALUES (850,'Islas Virgenes Estadounidenses');
INSERT INTO pais (k_codigo,n_nombre) VALUES (376,'Israel');
INSERT INTO pais (k_codigo,n_nombre) VALUES (380,'Italia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (388,'Jamaica');
INSERT INTO pais (k_codigo,n_nombre) VALUES (392,'Japón');
INSERT INTO pais (k_codigo,n_nombre) VALUES (832,'Jersey');
INSERT INTO pais (k_codigo,n_nombre) VALUES (400,'Jordania');
INSERT INTO pais (k_codigo,n_nombre) VALUES (398,'Kazajstan');
INSERT INTO pais (k_codigo,n_nombre) VALUES (404,'Kenia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (417,'Kirguistán');
INSERT INTO pais (k_codigo,n_nombre) VALUES (296,'Kiribati');
INSERT INTO pais (k_codigo,n_nombre) VALUES (414,'Kuwait');
INSERT INTO pais (k_codigo,n_nombre) VALUES (418,'Laos');
INSERT INTO pais (k_codigo,n_nombre) VALUES (426,'Lesotho');
INSERT INTO pais (k_codigo,n_nombre) VALUES (428,'Letonia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (430,'Liberia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (434,'Libia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (438,'Liechtenstein');
INSERT INTO pais (k_codigo,n_nombre) VALUES (440,'Lituania');
INSERT INTO pais (k_codigo,n_nombre) VALUES (442,'Luxemburgo');
INSERT INTO pais (k_codigo,n_nombre) VALUES (422,'Líbano');
INSERT INTO pais (k_codigo,n_nombre) VALUES (446,'Macao');
INSERT INTO pais (k_codigo,n_nombre) VALUES (450,'Madagascar');
INSERT INTO pais (k_codigo,n_nombre) VALUES (458,'Malasia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (454,'Malawi');
INSERT INTO pais (k_codigo,n_nombre) VALUES (462,'Maldivas');
INSERT INTO pais (k_codigo,n_nombre) VALUES (470,'Malta');
INSERT INTO pais (k_codigo,n_nombre) VALUES (466,'Malí');
INSERT INTO pais (k_codigo,n_nombre) VALUES (504,'Marruecos');
INSERT INTO pais (k_codigo,n_nombre) VALUES (474,'Martinica');
INSERT INTO pais (k_codigo,n_nombre) VALUES (480,'Mauricio');
INSERT INTO pais (k_codigo,n_nombre) VALUES (478,'Mauritania');
INSERT INTO pais (k_codigo,n_nombre) VALUES (175,'Mayotte');
INSERT INTO pais (k_codigo,n_nombre) VALUES (498,'Moldavia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (496,'Mongolia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (499,'Montenegro');
INSERT INTO pais (k_codigo,n_nombre) VALUES (500,'Montserrat');
INSERT INTO pais (k_codigo,n_nombre) VALUES (508,'Mozambique');
INSERT INTO pais (k_codigo,n_nombre) VALUES (484,'México');
INSERT INTO pais (k_codigo,n_nombre) VALUES (492,'Mónaco');
INSERT INTO pais (k_codigo,n_nombre) VALUES (516,'Namibia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (520,'Nauru');
INSERT INTO pais (k_codigo,n_nombre) VALUES (524,'Nepal');
INSERT INTO pais (k_codigo,n_nombre) VALUES (558,'Nicaragua');
INSERT INTO pais (k_codigo,n_nombre) VALUES (566,'Nigeria');
INSERT INTO pais (k_codigo,n_nombre) VALUES (570,'Niue');
INSERT INTO pais (k_codigo,n_nombre) VALUES (578,'Noruega');
INSERT INTO pais (k_codigo,n_nombre) VALUES (540,'Nueva Caledonia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (554,'Nueva Zelanda');
INSERT INTO pais (k_codigo,n_nombre) VALUES (562,'Níger');
INSERT INTO pais (k_codigo,n_nombre) VALUES (512,'Omán');
INSERT INTO pais (k_codigo,n_nombre) VALUES (586,'Pakistán');
INSERT INTO pais (k_codigo,n_nombre) VALUES (585,'Palaos');
INSERT INTO pais (k_codigo,n_nombre) VALUES (591,'Panamá');
INSERT INTO pais (k_codigo,n_nombre) VALUES (598,'Papua Nueva Guinea');
INSERT INTO pais (k_codigo,n_nombre) VALUES (600,'Paraguay');
INSERT INTO pais (k_codigo,n_nombre) VALUES (528,'Países Bajos');
INSERT INTO pais (k_codigo,n_nombre) VALUES (604,'Perú');
INSERT INTO pais (k_codigo,n_nombre) VALUES (258,'Polinesia Francesa');
INSERT INTO pais (k_codigo,n_nombre) VALUES (616,'Polonia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (620,'Portugal');
INSERT INTO pais (k_codigo,n_nombre) VALUES (630,'Puerto Rico');
INSERT INTO pais (k_codigo,n_nombre) VALUES (634,'Qatar');
INSERT INTO pais (k_codigo,n_nombre) VALUES (826,'Reino Unido');
INSERT INTO pais (k_codigo,n_nombre) VALUES (862,'República Bolibariana de Venezuela');
INSERT INTO pais (k_codigo,n_nombre) VALUES (140,'República Centroafricana');
INSERT INTO pais (k_codigo,n_nombre) VALUES (203,'República Checa');
INSERT INTO pais (k_codigo,n_nombre) VALUES (408,'República Democrática Popular de Corea');
INSERT INTO pais (k_codigo,n_nombre) VALUES (180,'República Democrática del Congo');
INSERT INTO pais (k_codigo,n_nombre) VALUES (214,'República Dominicana');
INSERT INTO pais (k_codigo,n_nombre) VALUES (178,'República de Congo');
INSERT INTO pais (k_codigo,n_nombre) VALUES (410,'República de Corea');
INSERT INTO pais (k_codigo,n_nombre) VALUES (242,'República de las Islas Fiyi');
INSERT INTO pais (k_codigo,n_nombre) VALUES (638,'Reunión');
INSERT INTO pais (k_codigo,n_nombre) VALUES (646,'Ruanda');
INSERT INTO pais (k_codigo,n_nombre) VALUES (642,'Rumania');
INSERT INTO pais (k_codigo,n_nombre) VALUES (643,'Rusia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (732,'Sahara Occidental');
INSERT INTO pais (k_codigo,n_nombre) VALUES (663,'Saint Martin (French part)');
INSERT INTO pais (k_codigo,n_nombre) VALUES (652,'Saint-Barthélemy');
INSERT INTO pais (k_codigo,n_nombre) VALUES (222,'Salvador');
INSERT INTO pais (k_codigo,n_nombre) VALUES (882,'Samoa');
INSERT INTO pais (k_codigo,n_nombre) VALUES (016,'Samoa Americana');
INSERT INTO pais (k_codigo,n_nombre) VALUES (659,'San Cristóbal y Nieves');
INSERT INTO pais (k_codigo,n_nombre) VALUES (674,'San Marino');
INSERT INTO pais (k_codigo,n_nombre) VALUES (666,'San Pedro y Miquelón');
INSERT INTO pais (k_codigo,n_nombre) VALUES (670,'San Vicente y las Granadinas');
INSERT INTO pais (k_codigo,n_nombre) VALUES (654,'Santa Helena, Ascensión y Tristan de Acuña');
INSERT INTO pais (k_codigo,n_nombre) VALUES (662,'Santa Lucía');
INSERT INTO pais (k_codigo,n_nombre) VALUES (336,'Santa Sede (Ciudad del Vaticano)');
INSERT INTO pais (k_codigo,n_nombre) VALUES (678,'Santo Tomé y Príncipe');
INSERT INTO pais (k_codigo,n_nombre) VALUES (686,'Senegal');
INSERT INTO pais (k_codigo,n_nombre) VALUES (688,'Serbia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (690,'Seychelles');
INSERT INTO pais (k_codigo,n_nombre) VALUES (694,'Sierra Leona');
INSERT INTO pais (k_codigo,n_nombre) VALUES (702,'Singapur');
INSERT INTO pais (k_codigo,n_nombre) VALUES (534,'Sint Maarten (Dutch part)');
INSERT INTO pais (k_codigo,n_nombre) VALUES (760,'Siria');
INSERT INTO pais (k_codigo,n_nombre) VALUES (706,'Somalia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (144,'Sri Lanka');
INSERT INTO pais (k_codigo,n_nombre) VALUES (748,'Suazilandia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (710,'Sudáfrica');
INSERT INTO pais (k_codigo,n_nombre) VALUES (729,'Sudán');
INSERT INTO pais (k_codigo,n_nombre) VALUES (728,'Sudán del Sur');
INSERT INTO pais (k_codigo,n_nombre) VALUES (752,'Suecia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (756,'Suiza');
INSERT INTO pais (k_codigo,n_nombre) VALUES (740,'Surinam');
INSERT INTO pais (k_codigo,n_nombre) VALUES (744,'Svalbard y Jan Mayen');
INSERT INTO pais (k_codigo,n_nombre) VALUES (764,'Tailandia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (158,'Taiwan (Formosa)');
INSERT INTO pais (k_codigo,n_nombre) VALUES (834,'Tanzania');
INSERT INTO pais (k_codigo,n_nombre) VALUES (762,'Tayikistán');
INSERT INTO pais (k_codigo,n_nombre) VALUES (086,'Territorio Británico del  Océano Índico');
INSERT INTO pais (k_codigo,n_nombre) VALUES (260,'Territorios Australes Franceses');
INSERT INTO pais (k_codigo,n_nombre) VALUES (626,'Timor Oriental');
INSERT INTO pais (k_codigo,n_nombre) VALUES (768,'Togo');
INSERT INTO pais (k_codigo,n_nombre) VALUES (772,'Tokelau');
INSERT INTO pais (k_codigo,n_nombre) VALUES (776,'Tonga');
INSERT INTO pais (k_codigo,n_nombre) VALUES (780,'Trinidad y Tobago');
INSERT INTO pais (k_codigo,n_nombre) VALUES (795,'Turkmenistan');
INSERT INTO pais (k_codigo,n_nombre) VALUES (792,'Turquía');
INSERT INTO pais (k_codigo,n_nombre) VALUES (798,'Tuvalu');
INSERT INTO pais (k_codigo,n_nombre) VALUES (788,'Túnez');
INSERT INTO pais (k_codigo,n_nombre) VALUES (804,'Ucrania');
INSERT INTO pais (k_codigo,n_nombre) VALUES (800,'Uganda');
INSERT INTO pais (k_codigo,n_nombre) VALUES (858,'Uruguay');
INSERT INTO pais (k_codigo,n_nombre) VALUES (860,'Uzbekistan');
INSERT INTO pais (k_codigo,n_nombre) VALUES (548,'Vanuatu');
INSERT INTO pais (k_codigo,n_nombre) VALUES (704,'Vietnam');
INSERT INTO pais (k_codigo,n_nombre) VALUES (876,'Wallis y Futuna');
INSERT INTO pais (k_codigo,n_nombre) VALUES (887,'Yemen');
INSERT INTO pais (k_codigo,n_nombre) VALUES (262,'Yibuti');
INSERT INTO pais (k_codigo,n_nombre) VALUES (894,'Zambia');
INSERT INTO pais (k_codigo,n_nombre) VALUES (716,'Zimbabwe');

